### PR TITLE
Server updated to express

### PR DESCRIPTION
**Pull request by kindlehl**
Landscape.jpg and space.jpg were somehow lost and I didn't want to go through the headache of reviving them from their graves. I've put my own copies of them just to verify that the page's requests were being handeled fine. 

There was a slight change in the database query method. You now need to specify "query" before the ?. You can see the google doc for more information.

File hierarchy is easier on the eyes. You do not have to specify a path to an image. The serving stack will look into the images folder everytime a .jpg or .png file is requested. It is also very easy to add more file formats if you need to. All pages seem to work fine, other than the images that I lost not rendering.

I will work to templatize the bookshelf page. I expect you all to write your own Express middleware for your database stuff (I know Khoa wanted to do database stuff as well).

### CODE REVIEW

**Comment by chasestubb** [comment]
Sorry about that. I removed landscape and space.jpg because they were only temporary. I should’ve at least replaced the file names in the code too. I think all the background photos are uploaded now. 

I’m back from my long trip now, and I hope my job search isn’t too time consuming for the next two weeks (I was interviewing in Portland all Tuesday) so now I’m spending 12 hours every day cranking in school. I’m in a tough situation where I’ll probably have to work pretty hard every day for the next two weeks. I like to think I’ll have a lot of time for this project but we’ll see.

**Comment by chasestubb** [comment]
Cool beans

**Review by ghost — APPROVED** [review]
Looks good to me!

Do you want me to merge this now, or wait until everyone has done a review of the changes?

**Comment by kindlehl** [comment]
Ill merge this so I can start working on the database authenticcation on OSU_Secure

**Pull request merged**
